### PR TITLE
hclsyntax: Source range of IndexExpr, SplatExpr, and RelativeTraversalExpr must cover whole expression

### LINKED ISSUE #327: Panic in hclwrite parser: didn't find any token of type TokenIdent
Originally reported over in apparentlymart/terraform-clean-syntax#3 by @mattsawyer77.

On certain input, it seems that the analysis of traversals in expressions fails and produces a panic:

```
panic: didn't find any token of type TokenIdent

goroutine 1 [running]:
github.com/hashicorp/hcl/v2/hclwrite.inputTokens.PartitionType(0xc00036be20, 0x0, 0x0, 0xc0003c5fd8, 0x0, 0x0, 0x49, 0x0, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:88 +0x580
github.com/hashicorp/hcl/v2/hclwrite.inputTokens.PartitionTypeSingle(0xc00036be20, 0x0, 0x0, 0xc0003c5fd8, 0x0, 0x0, 0xc000000049, 0x0, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:92 +0xe3
github.com/hashicorp/hcl/v2/hclwrite.parseTraversalStep(0x130e460, 0xc000298050, 0xc00036be20, 0x0, 0x0, 0xc0003c5fd8, 0x0, 0x0, 0xc00036be20, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:395 +0x364
github.com/hashicorp/hcl/v2/hclwrite.parseTraversal(0xc000263280, 0x3, 0x4, 0xc00036be20, 0x0, 0x0, 0xc0003c5fd8, 0x0, 0x0, 0xc00036be20, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:377 +0x3da
github.com/hashicorp/hcl/v2/hclwrite.parseExpression(0x130faa0, 0xc0000b6700, 0xc00036be20, 0x2, 0x2, 0xc0003c5fd8, 0x2, 0x2, 0x18b)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:356 +0x175
github.com/hashicorp/hcl/v2/hclwrite.parseAttribute(0xc00028bea0, 0xc00036ba60, 0x0, 0x0, 0xc0003c5f88, 0x0, 0x0, 0xc00036b9a0, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:260 +0xaf4
github.com/hashicorp/hcl/v2/hclwrite.parseBodyItem(0x130cc20, 0xc00028bea0, 0xc00036b9a0, 0x17, 0x17, 0xc0003c5f78, 0x17, 0x17, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:217 +0x632
github.com/hashicorp/hcl/v2/hclwrite.parseBody(0xc0000b5a20, 0xc00036af20, 0x33, 0x33, 0xc0003c5e98, 0x33, 0x33, 0x0, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:193 +0x68d
github.com/hashicorp/hcl/v2/hclwrite.parseBlock(0xc000286b40, 0xc00036af20, 0x0, 0x0, 0xc0003c5e98, 0x0, 0x0, 0xc00036aa40, 0x5, 0x5, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:329 +0xf72
github.com/hashicorp/hcl/v2/hclwrite.parseBodyItem(0x130cc60, 0xc000286b40, 0xc00036a9e0, 0x70, 0x70, 0xc0003c5e28, 0x70, 0x70, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:219 +0x4f7
github.com/hashicorp/hcl/v2/hclwrite.parseBody(0xc0000b5b80, 0xc00033c000, 0x836, 0xa00, 0xc0003c2000, 0x836, 0x836, 0x0, 0x0, 0x0, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:193 +0x68d
github.com/hashicorp/hcl/v2/hclwrite.parse(0xc000102000, 0x38eb, 0x3aeb, 0xc0000e41e0, 0x1c, 0x1, 0x1, 0x0, 0xc0000c3c48, 0xc000000000, ...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/parser.go:53 +0x2e4
github.com/hashicorp/hcl/v2/hclwrite.ParseConfig(...)
        /Users/sawyer/gocode/pkg/mod/github.com/hashicorp/hcl/v2@v2.1.0/hclwrite/public.go:27
main.processFile(0xc0000e41e0, 0x1c, 0x1a4)
        /Users/sawyer/terraform-clean-syntax/main.go:75 +0xc8
main.processItem(0xc0000e41e0, 0x1c)
        /Users/sawyer/terraform-clean-syntax/main.go:52 +0x25d
main.processDir(0x7ffeefbff63f, 0x16)
        /Users/sawyer/terraform-clean-syntax/main.go:64 +0x119
main.processItem(0x7ffeefbff63f, 0x16)
        /Users/sawyer/terraform-clean-syntax/main.go:44 +0x17b
main.main()
        /Users/sawyer/terraform-clean-syntax/main.go:30 +0xca
```

It looks like the relevant bit of code is here-ish:

https://github.com/hashicorp/hcl/blob/7f9aa845c107b03e33729886a8b5c5f4be74766a/hclwrite/parser.go#L391-L400

This codepath is assuming that any traversal step marked by the main parser as being a root (the beginning of a traversal) or an attribute (something that comes after a `.`) will contain an identifier in it. On the surface that seems like a reasonable assumption, but apparently there is at least one exceptional case where that isn't true.

### PR DESCRIPTION
**Pull request by apparentlymart**
Some `hclsyntax` callers make the (reasonable) assumption that the overall source range of an expression will be a superset of all of the ranges of its child expressions, for purposes such as extraction of source code snippets, parse tree annotation in hclwrite, text editor analysis functions like "go to reference", etc.

The `IndexExpr` type was not previously honoring that assumption, since its source range was placed around only the bracket portion. That is a good region to use when reporting errors relating to the index operation, but it is not a faithful representation of the full extent of the expression.

In order to meet both of these requirements at once, `IndexExpr` now has both `SrcRange` covering the entire expression and `BracketRange` covering the index part delimited by brackets. We can then use `BracketRange` in our error messages but return `SrcRange` as the result of the general
`Range` method that is common to all expression types.

While investigating this I noticed that both `SplatExpr` (both full and attribute-only variations) and `RelativeTraversalExpr` had a similar issue, and have also corrected those in a similar way. They were already separately tracking the "operator part" of the expression for error reporting purposes, so no additional field was required for these ones.

This also includes a new test case for `hclwrite` showing that this PR fixes #327, by allowing `hclwrite`'s analyzer to determine the correct bounds of an index expression in order to partition the tokens correctly in its physical syntax tree.

### CODE REVIEW

File: hclsyntax/parser.go [hunk 1]
```diff
@@ -867,8 +867,9 @@ Traversal:
 						Collection: ret,
 						Key:        keyExpr,
 
-						SrcRange:  rng,
-						OpenRange: open.Range,
+						SrcRange:     hcl.RangeBetween(from.Range(), rng),
```
Comment (apparentlymart) [inline hclsyntax/parser.go]: `from` in this function is the expression that the subsequent postfix operators are applying to, so in an expression like `foo[bar]` the `from` variable refers to the `foo` expression.

File: hclsyntax/parser_test.go [hunk 2]
```diff
@@ -1872,6 +1876,91 @@ block "valid" {}
...
+											},
+										},
+									},
+
+									SrcRange: hcl.Range{
+										Start: hcl.Pos{Line: 1, Column: 8, Byte: 7},
+										End:   hcl.Pos{Line: 1, Column: 26, Byte: 25},
+									},
+								},
+								Each: &AnonSymbolExpr{
```
Comment (apparentlymart) [inline hclsyntax/parser_test.go]: `SplatExpr` is a bit of an odd one in that it evaluates this `Each` expression multiple times, each time applying a localized substitution for the `AnonSymbolExpr` given in `Item` below. In this test case there is nothing after the `[*]` in the input, so the "each" expression is just the anonymous symbol itself; a `[*]` without subsequent traversals on a list expression just redundantly re-produces the list it was applied to.

File: hclwrite/parser_test.go [hunk 3]
```diff
@@ -555,6 +555,78 @@ func TestParse(t *testing.T) {
 				},
 			},
 		},
+		{
+			"a = foo[bar]\n",
```
Comment (apparentlymart) [inline hclwrite/parser_test.go]: What `hclwrite`'s "parser" is doing here is turning the raw token stream into a physical parse tree, as opposed to the _abstract_ parse tree in `hclsyntax`.

It uses the source ranges from `hclsyntax` to find the bounds of the attribute definition and its expression, and then it further marks out the traversals inside the expression in order to enable "rename symbol"-type operations in text editors to surgically update the references without affecting the surrounding tokens.

This case was panicking before because the `foo` token was not being indicated by `hclsyntax` as part of the expression, and so when the traversal analyzer attempted to find the `TokenIdent` to learn the name it was looking into an empty token sequence.

File: hclwrite/parser_test.go [hunk 4]
```diff
@@ -555,6 +555,78 @@ func TestParse(t *testing.T) {
...
+									{
+										Type: "Traversal",
+										Children: []TestTreeNode{
+											{
+												Type: "TraverseName",
+												Children: []TestTreeNode{
+													{
+														Type: "identifier",
+														Val:  " foo",
+													},
```
Comment (apparentlymart) [inline hclwrite/parser_test.go]: This is the identifier extracted from the `foo` token, which was previously excluded from the parent expression by the faulty source boundaries on the `IndexExpr` node.

File: hclsyntax/expression.go [hunk 5]
```diff
@@ -631,7 +632,7 @@ func (e *IndexExpr) Value(ctx *hcl.EvalContext) (cty.Value, hcl.Diagnostics) {
 	diags = append(diags, collDiags...)
 	diags = append(diags, keyDiags...)
 
-	val, indexDiags := hcl.Index(coll, key, &e.SrcRange)
+	val, indexDiags := hcl.Index(coll, key, &e.BracketRange)
```
Comment (apparentlymart) [inline hclsyntax/expression.go]: This final argument is what `hcl.Index` uses as the subject of any diagnostics it produces if the index operation fails. I've changed this so that errors relating to incorrectly-typed or incorrectly-valued indices will continue to highlight only the bracketed part, making it clearer which part of the expression is faulty.
